// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Dataset struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Public      bool
}

type DatasetField struct {
	ID          uuid.UUID
	DatasetID   uuid.UUID
	Name        string
	DataType    string
	Description sql.NullString
	CreatedAt   time.Time
}

type DatasetRecord struct {
	ID        uuid.UUID
	DatasetID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PendingUser struct {
	ID           uuid.UUID
	Email        string
	Username     string
	PasswordHash string
	Token        string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type RecordValue struct {
	RecordID uuid.UUID
	FieldID  uuid.UUID
	Value    sql.NullString
}

type User struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Email               string
	Username            string
	PasswordHash        string
	FailedLoginAttempts sql.NullInt32
	LastFailedAttempt   sql.NullTime
	LockedUntil         sql.NullTime
}
