export const chartTypeByMethod = {
  grouped: 'bar',
  droppedRows: 'bar',
  filledMissingWith: 'bar',
  logTransform: 'line',
  normalizedColumn: 'line',
  standardizedColumn: 'line',
  pearson: 'bar',
  spearman: 'bar',
  correlationMatrix: 'matrix',
  mean: 'bar',
  median: 'bar',
  mode: 'bar',
  variance: 'bar',
  min: 'bar',
  max: 'bar',
  sum: 'bar',
  stddev: 'bar',
  range: 'bar',
  count: 'bar',
  histogram: 'bar',
  kde: 'line',
  filterSort: 'bar',
  ZScore: 'line',
  IQR: 'bar',
  boxPlot: 'boxplot',
  pivot: 'stackedBar',
};
