export const chartTypeByMethod = {
  grouped: 'bar',
  droprowswithmissing: 'bar',
  filledmissingwith: 'bar',
  applylogtransformation: 'line',
  normalizedcolumn: 'line',
  standardizedcolumn: 'line',
  pearson: 'bar',
  spearman: 'bar',
  correlationmatrix: 'matrix',
  mean: 'bar',
  median: 'bar',
  mode: 'bar',
  variance: 'bar',
  min: 'bar',
  max: 'bar',
  sum: 'bar',
  stddev: 'bar',
  range: 'bar',
  count: 'bar',
  histogram: 'bar',
  kde: 'line',
  filtersort: 'bar',
  zscore: 'line',
  iqr: 'bar',
  boxplot: 'boxplot',
  pivot: 'stackedBar',
};
